#!/usr/bin/env python3
"""tp20 — the oscillator pool's IDs. Reads every SYN_OSC_A_* constant in Source/ParameterIDs.hpp and
(1) appends the E/F/G/H twins to ParameterIDs.hpp if the bank-2 block is not there yet, and
(2) regenerates Source/OscBankIds.h: the A–D → E–H remap tables rawParamB() resolves through, plus the
8-wide per-knob tables (kOsc_ENGINE[8] ...) the message-thread loops index by oscillator.
Run from plugins/Terrain:  python3 scripts/gen_osc_bank_ids.py
"""
import re, os, sys
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here)
pids = os.path.join(root, 'Source', 'ParameterIDs.hpp'); out = os.path.join(root, 'Source', 'OscBankIds.h')
src = open(pids).read()
names, seen = [], set()
for m in re.finditer(r'constexpr char SYN_OSC_A_([A-Z0-9_]+)\[\]', src):
    if m.group(1) not in seen: seen.add(m.group(1)); names.append(m.group(1))
for L in 'BCD':
    missing = [n for n in names if f'SYN_OSC_{L}_{n}[]' not in src]
    if missing: sys.exit(f'oscillator {L} lacks {missing}: the A/B/C/D sets must match before E-H can be generated')
if 'constexpr char SYN_OSC_E_ENGINE[]' not in src:
    blk = ['', '    // ══ tp20 — THE OSCILLATOR POOL, BANK 2 (E–H). GENERATED from the A set by scripts/gen_osc_bank_ids.py —',
           '    //    every knob A carries, E/F/G/H carry, same name, letter swapped. Instance A–D keep their IDs; these are',
           '    //    APPENDED (the parameter law). A bank-2 voice is an unmodified SynthVoice whose A/B/C/D slots ARE E/F/G/H.']
    for L in 'EFGH':
        blk.append(f'    // ── OSC {L} ──')
        blk += [f'    constexpr char SYN_OSC_{L}_{n}[] = "SYN_OSC_{L}_{n}";' for n in names]
    for dev in ('RVB', 'DLY', 'DST'):
        blk.append(f'    constexpr char SYN_{dev}_SRC_E[] = "SYN_{dev}_SRC_E"; constexpr char SYN_{dev}_SRC_F[] = "SYN_{dev}_SRC_F";')
        blk.append(f'    constexpr char SYN_{dev}_SRC_G[] = "SYN_{dev}_SRC_G"; constexpr char SYN_{dev}_SRC_H[] = "SYN_{dev}_SRC_H";')
    blk.append('    constexpr int kOscBanks = 2, kOscPerBank = 4, kOscCount = kOscBanks * kOscPerBank;   // tp20 — A–D = bank 0, E–H = bank 1')
    idx = src.rstrip().rfind('\n}')
    src = src[:idx] + '\n' + '\n'.join(blk) + '\n' + src[idx:]
    open(pids, 'w').write(src); print('ParameterIDs.hpp: appended the E-H block')
# tp104 — SYN_OSC_x_OUT (tp30) is declared for A–D only and was never in the remap: the bank-1 gather keeps reading
#   bank 0's constant for it, exactly as since tp30. Kept out here so a regeneration cannot change what bank 1 reads.
A_ONLY = ['OUT']
names = [n for n in names if n not in A_ONLY]
missingE = [n for n in names if f'SYN_OSC_E_{n}[]' not in src]
if missingE: sys.exit(f'the E block exists but lacks {missingE}: append them by hand (append-only) or regenerate')
hdr = ['#pragma once',
       '// tp20 — GENERATED by scripts/gen_osc_bank_ids.py from ParameterIDs.hpp. The bank-1 gather reads the A–D constants',
       '// through rawParamB(), which maps each A–D pointer to its E–H twin here (A→E, B→F, C→G, D→H). Do not hand-edit.',
       '#include "ParameterIDs.hpp"', 'namespace ParameterIDs {']
frm, to = [], []
for a, e in zip('ABCD', 'EFGH'):
    for n in names: frm.append(f'SYN_OSC_{a}_{n}'); to.append(f'SYN_OSC_{e}_{n}')
    for dev in ('RVB', 'DLY', 'DST'): frm.append(f'SYN_{dev}_SRC_{a}'); to.append(f'SYN_{dev}_SRC_{e}')
hdr.append(f'inline constexpr int kOscRemapCount = {len(frm)};')
hdr.append('inline constexpr const char* const kOscRemapFrom[kOscRemapCount] = {')
hdr += ['    ' + ', '.join(frm[i:i+4]) + ',' for i in range(0, len(frm), 4)]; hdr.append('};')
hdr.append('inline constexpr const char* const kOscRemapTo[kOscRemapCount] = {')
hdr += ['    ' + ', '.join(to[i:i+4]) + ',' for i in range(0, len(to), 4)]; hdr.append('};')
TABLES = ['ENGINE','ENABLE','WT_PRESET','WT_FRAME','HARM_TABLE','HARM_MODE','SPECTRAL_TYPE','SPECTRAL_AMT','SPECTRAL_LO','SPECTRAL_HI',
          'URANGE','PHASE','LEVEL','MUTE','SOLO','F1MIX','F2MIX','SAMPLE_LOOP_MODE','SAMPLE_LOOP_START','SAMPLE_LOOP_END','WARP_MODE',
          'WARP_AMOUNT','WARP2_MODE','WARP2_AMT','FOLD_AMT','FRAME_SPREAD','PHASE_MODE','PAN','OCT','SEMI','CENT',
          # tp20b — the three the display path needs and the first pass missed. Their absence is what
          # left wtDispEffective/getWarpCurveJson indexing hand-written [4] tables with an index up to 7.
          'FOLD_SHAPE','WVAR','W2VAR',
          # tp104 — the Organics engine's twelve (the message-thread lazy arm / instrument requests index them by oscillator)
          'ORG_INST','ORG_ARTIC','ORG_DYNAMICS','ORG_TONE','ORG_BODY','ORG_ATTACK','ORG_HUMAN','ORG_RELEASE','ORG_NOISE','ORG_SUSTAIN','ORG_VELOCITY','ORG_IMAGE',
          # tp105 — Vibrato (knob 3) + the Organics back panel
          'ORG_VIBRATO','ORG_VIBRATE','ORG_VIBDELAY','ORG_VCURVE','ORG_TUNING',
          # tp114 — the back panel's Start
          'ORG_START']
for n in TABLES:
    if n in names:
        hdr.append(f'inline constexpr const char* const kOsc_{n}[kOscCount] = {{ ' + ', '.join(f'SYN_OSC_{L}_{n}' for L in 'ABCDEFGH') + ' };')
hdr.append("inline constexpr char kOscLetter[kOscCount] = { 'A','B','C','D','E','F','G','H' };")
# tp20 — the FLOW cards' instance-1 ids (constants), so the processor can remap FLOW_ARP_X -> FLOW_ARP2_X by POINTER
flow = []
for m in re.finditer(r'constexpr char (FLOW_(?:ARP|SEQ|CHOP|GLI)_[A-Z0-9_]+)\[\]', src):
    # tp104 — the tp30 route pills (FLOW_CHOP_SRC_x / FLOW_GLI_SRC_x) were declared after tp20 generated this list and
    #   never joined it; adding them now would re-point what instances 2..4 read. Kept out: a regeneration is a no-op for flow.
    if re.match(r'FLOW_(?:CHOP|GLI)_SRC_[A-Z]+$', m.group(1)): continue
    if m.group(1) not in flow: flow.append(m.group(1))
hdr.append(f'inline constexpr int kFlowIdCount = {len(flow)};   // the Flow cards\' instance-1 constants (Arp / Seq=Chop macros / Chop / Glitch)')
hdr.append('inline constexpr const char* const kFlowIds[kFlowIdCount] = {')
hdr += ['    ' + ', '.join(flow[i:i+4]) + ',' for i in range(0, len(flow), 4)]; hdr.append('};')
hdr.append('} // namespace ParameterIDs')
open(out, 'w').write('\n'.join(hdr) + '\n'); print(f'OscBankIds.h: {len(names)} knobs per oscillator, {len(frm)} remaps')
