#!/usr/bin/env python3
"""tp25 — freeze the factory wavetable library into Source/FactoryTableIds.h.

WHY GENERATED AND WHY FROZEN. SYN_FILTER1/2_TBL is an AudioParameterChoice, and a choice list is
part of the saved state's meaning: index N must name the same table forever. If the list were
built by scanning the folder at startup, adding, renaming or removing one .flac would silently
repoint every saved patch's filter table. So the order is fixed here, in the binary, sorted by
(category, name), and the list only ever GROWS at the end.

    python3 scripts/gen_factory_tables.py
"""
import os, glob, json

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
WT = os.path.join(ROOT, 'Resources', 'Wavetables')
OUT = os.path.join(ROOT, 'Source', 'FactoryTableIds.h')

rows = []
for p in sorted(glob.glob(os.path.join(WT, '*', '*.flac'))):
    cat = os.path.basename(os.path.dirname(p))
    name = os.path.splitext(os.path.basename(p))[0]
    rows.append((cat, name))
rows.sort(key=lambda r: (r[0].lower(), r[1].lower()))

names = [r[1] for r in rows]
assert len(names) == len(set(names)), 'table names are not unique — the choice list needs qualifying'

cats = sorted({r[0] for r in rows}, key=str.lower)
h = []
h.append('#pragma once')
h.append('// ' + '=' * 96)
h.append('//  FactoryTableIds.h — GENERATED by scripts/gen_factory_tables.py. Do not hand-edit.')
h.append('//')
h.append('//  The factory wavetable library, frozen in one order so that SYN_FILTER1/2_TBL can name it.')
h.append('//  A choice parameter\'s index IS its saved meaning, so this list may only ever grow at the END:')
h.append('//  re-sorting it, or letting a folder scan decide it, would repoint every saved patch\'s filter')
h.append('//  table. Each entry is one .flac of %d samples = 128 cycles x 2048, mono.' % 262144)
h.append('// ' + '=' * 96)
h.append('#include <cstddef>')
h.append('')
h.append('namespace ParameterIDs')
h.append('{')
h.append('    inline constexpr int kFactoryTableCount = %d;' % len(rows))
h.append('    inline constexpr int kFactoryTableCatCount = %d;' % len(cats))
h.append('')
h.append('    // display name — unique across the whole library (asserted by the generator)')
h.append('    inline constexpr const char* const kFactoryTableName[kFactoryTableCount] = {')
for i in range(0, len(rows), 4):
    h.append('        ' + ', '.join(json.dumps(n) for n in names[i:i + 4]) + ',')
h.append('    };')
h.append('')
h.append('    // path relative to the installed Resources/Wavetables folder (wtFactoryRoot())')
h.append('    inline constexpr const char* const kFactoryTableRel[kFactoryTableCount] = {')
rel = ['%s/%s.flac' % (c, n) for c, n in rows]
for i in range(0, len(rel), 2):
    h.append('        ' + ', '.join(json.dumps(r) for r in rel[i:i + 2]) + ',')
h.append('    };')
h.append('')
h.append('    // the category each entry belongs to, index for index')
h.append('    inline constexpr const char* const kFactoryTableCat[kFactoryTableCount] = {')
cl = [c for c, n in rows]
for i in range(0, len(cl), 6):
    h.append('        ' + ', '.join(json.dumps(c) for c in cl[i:i + 6]) + ',')
h.append('    };')
h.append('')
h.append('    inline constexpr const char* const kFactoryTableCatNames[kFactoryTableCatCount] = {')
h.append('        ' + ', '.join(json.dumps(c) for c in cats))
h.append('    };')
h.append('} // namespace ParameterIDs')
open(OUT, 'w').write('\n'.join(h) + '\n')

# ── and the same frozen order, for the UI's Tables category ──────────────────────────────────
HTML = os.path.join(ROOT, 'Source', 'ui', 'public', 'index.html')
BEGIN = '      /* @gen:factory-tables — generated by scripts/gen_factory_tables.py, do not hand-edit */'
END = '      /* @end:factory-tables */'
js = [BEGIN,
      '      /* The 454 factory wavetables, in the SAME frozen order as Source/FactoryTableIds.h, which is the',
      '         order SYN_FILTER1/2_TBL appends them in after the built-in roster. The built-in names are NOT',
      '         repeated here: they are read off the oscillator preset <select> by option VALUE at use time, so',
      '         there is one roster, not a copy of one. */',
      '      window.__factoryTables=[']
for i in range(0, len(names), 6):
    js.append('        ' + ', '.join(json.dumps(n) for n in names[i:i + 6]) + ',')
js.append('      ];')
js.append(END)
block = '\n'.join(js)
src = open(HTML, encoding='utf-8').read()
if BEGIN in src:
    i, j = src.index(BEGIN), src.index(END) + len(END)
    src = src[:i] + block + src[j:]
else:
    anchor = '      const FILTER_TYPES = ['
    assert src.count(anchor) == 1, 'FILTER_TYPES anchor not unique'
    src = src.replace(anchor, block + '\n' + anchor)
open(HTML, 'w', encoding='utf-8').write(src)
print('index.html: window.__factoryTables = %d names' % len(names))
print('FactoryTableIds.h: %d tables across %d categories' % (len(rows), len(cats)))
for c in cats:
    print('   %-14s %d' % (c, sum(1 for x, _ in rows if x == c)))
