#!/usr/bin/env python3
"""tp24 — bake the VERIFIED-IN-TUNE one-shot list into index.html.

Source of truth is Tests/fixtures/oneshot_tuning.csv, produced by scripts/oneshot_tuning.py.
A file earns its place only by MEASURING within TOL cents of C with the estimator confident;
"uncertain" is not good enough, because the dice must never load a sound whose pitch nobody has
actually established. Run this after re-measuring; Tests/dice_rules_gate.js re-derives the list
from the CSV and fails if the two ever disagree.

    python3 scripts/gen_tuned_oneshots.py
"""
import csv, os, json, collections

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV = os.path.join(ROOT, 'Tests', 'fixtures', 'oneshot_tuning.csv')
HTML = os.path.join(ROOT, 'Source', 'ui', 'public', 'index.html')
TOL = 15.0

BEGIN = '  /* @gen:tuned-oneshots — generated by scripts/gen_tuned_oneshots.py, do not hand-edit */'
END = '  /* @end:tuned-oneshots */'

cats = collections.defaultdict(list)
total = 0
for r in csv.DictReader(open(CSV)):
    total += 1
    if int(r['uncertain']):
        continue
    if abs(float(r['cents_from_C'])) > TOL:
        continue
    c, n = r['path'].split('/', 1)
    cats[c].append(n)

kept = sum(len(v) for v in cats.values())
lines = [BEGIN,
         '  /* %d of %d factory one-shots MEASURED within %.0f cents of C (scripts/oneshot_tuning.py).' % (kept, total, TOL),
         '     The dice loads nothing else: no drums, no ambiences, and nothing whose pitch the analyser',
         '     would not commit to. Max: "they actually have to be tuned to C ... not just, oh, pretend C." */',
         '  var TUNED_ONESHOTS={']
for c in sorted(cats):
    names = ','.join(json.dumps(n) for n in sorted(cats[c]))
    lines.append('    %s:[%s],' % (json.dumps(c), names))
lines.append('  };')
lines.append('  var TUNED_SET=(function(){ var m={}; for(var c in TUNED_ONESHOTS){ m[c]={}; TUNED_ONESHOTS[c].forEach(function(n){ m[c][n]=1; }); } return m; })();')
lines.append('  function tunedIn(c){ return TUNED_ONESHOTS[c]||[]; }')
lines.append(END)
block = '\n'.join(lines)

src = open(HTML, encoding='utf-8').read()
if BEGIN in src:
    i, j = src.index(BEGIN), src.index(END) + len(END)
    src = src[:i] + block + src[j:]
else:
    anchor = "  var DRUMCATS=['Drums','808'];"
    assert src.count(anchor) == 1, 'anchor not found (or not unique)'
    src = src.replace(anchor, block)
open(HTML, 'w', encoding='utf-8').write(src)
print('%d verified one-shots baked in, across %d categories' % (kept, len(cats)))
for c in sorted(cats):
    print('   %-7s %d' % (c, len(cats[c])))
