const puppeteer=require('puppeteer-core'); const fs=require('fs'),path=require('path'); const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const sim=fs.readFileSync(process.cwd()+'/Tests/_ui_lockin_sim.js','utf8'); const stubSrc=sim.slice(sim.indexOf('const stub = () => {'),sim.indexOf('// ── the instruments'));
const src=fs.readFileSync('Source/ui/public/index.html','utf8'); const PAGE=path.join(require('os').tmpdir(),'tp72s.html'); fs.writeFileSync(PAGE,src);
const OUT=process.argv[2]||'/tmp/shp72';
(async()=>{ const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:'new',args:['--no-sandbox']});
 const p=await b.newPage(); await p.setViewport({width:1200,height:900,deviceScaleFactor:2}); await p.evaluateOnNewDocument(stubSrc+'\nstub(); ["VOL","TIME","FILT","PAN","REP","DRIVE","PHASE","CRUSH"].forEach(function(L,i){ window.__params["FLOW_CHOP_"+L+"_ON"]=i?0:1; window.__params["FLOW_CHOP_"+L+"_DEPTH"]=1; window.__params["FLOW_CHOP_"+L+"_RATE"]=4/7; window.__params["FLOW_CHOP_"+L+"_MODE"]=(L==="DRIVE"?5/22:0); window.__params["FLOW_CHOP_"+L+"_TRIG"]=0; });');
 await p.goto('file://'+PAGE,{waitUntil:'load'}); await sleep(2000); await p.evaluate(()=>{ document.documentElement.setAttribute('data-theme','dark'); window.setActivePanel('syn'); }); await sleep(500);
 await p.evaluate(async()=>{ const c=window.__flowCardOf('chop',1); c.open(); await new Promise(r=>setTimeout(r,600));
   window.__flowFeedPush={arp:[],gli:[],chop:[{ph:[0.31,0,0,0,0,0,0,0],v:[1,0,0,0,0,0,0,0],ln:[1,0,0,0,0,0,0,0],tr:[0,0,0,0,0,0,0,0],b:120,on:1,pl:1}]}; });
 await sleep(300);
 const card=await p.$('.ti-card.shp-ext');
 await card.screenshot({path:OUT+'_shape.png'});
 await p.evaluate(async()=>{ const card=document.querySelector('.ti-card.shp-ext'); card.querySelectorAll('.fx .fxb')[2].click(); await new Promise(r=>setTimeout(r,100)); [...card.querySelectorAll('.tab')].find(t=>t.textContent==='Target').click(); }); await sleep(300);
 await card.screenshot({path:OUT+'_target.png'});
 await p.evaluate(async()=>{ const card=document.querySelector('.ti-card.shp-ext'); [...card.querySelectorAll('.tab')].find(t=>t.textContent==='Clock').click(); }); await sleep(300);
 await card.screenshot({path:OUT+'_clock.png'});
 await p.evaluate(async()=>{ const card=document.querySelector('.ti-card.shp-ext'); card.querySelectorAll('.fx .fxb')[5].click(); await new Promise(r=>setTimeout(r,100)); [...card.querySelectorAll('.tab')].find(t=>t.textContent==='Target').click(); const S=window.__tiDice.chop.S; S.set('tension5',.85); S.set('swing5',.4); }); await sleep(300);
 await card.screenshot({path:OUT+'_drive.png'});
 await b.close(); console.log('shots at '+OUT); })();
