#!/usr/bin/env python3
# ══════════════════════════════════════════════════════════════════════════════════════════════
#  extract_morph_life.py — fb636 F4 · SLICE THE SHIPPING MORPH-BUFFER LIFETIME VERBATIM into a
#  header Tests/morph_pages_cert.cpp compiles (the extract_import_life.py idiom).
#
#      python3 Tests/extract_morph_life.py <PluginProcessor.h> <PluginProcessor.cpp> <out.h> [--mutate M]
#
#  WHAT IS CUT. From the header: `struct ImportSlot` and `struct MorphSlot` (brace-balanced, bytes as
#  they ship) and the inline `wavetableForOsc` — the audio thread's read of both. From the .cpp:
#  importGraceOver, publishMorph, freeRetiredMorphs and rebuildMorphIfNeeded (the None branch, the
#  skip gate, the retire cooldown, the claim, the build and the publish), with ONE token rewritten:
#  `TerrainAudioProcessor::` -> `MorphLife::` (the cert's host class). The cert then drives these
#  exact bytes: the timer on its main thread, the audio read on another, against page-backed tables.
#
#  THE MUTATIONS (the generated header only; Source is never written). Every anchor must fire exactly
#  once, or this exits 2 — a control that cannot fire is not a control:
#      nofence    freeRetiredMorphs stops waiting for the audio block (the grace AND audioReadingIdx) -> L1 red
#      nohold     freeRetiredMorphs frees a retired buffer without the hold                           -> M2 red
#      cooldown   freeRetiredMorphs writes rebuild state (retireCooldown = 0)                         -> M5 red
#      stampeach  the None branch stamps BOTH buffers every tick (the F4 skeptic's first trap)        -> M3 red
#
#  ⚠️ If any piece moves or is renamed this exits non-zero with the reason: a LOUD red, never a cert
#  that quietly compiles nothing.
# ══════════════════════════════════════════════════════════════════════════════════════════════
import re, sys

FUNCS = ["importGraceOver", "publishMorph", "freeRetiredMorphs", "rebuildMorphIfNeeded"]
MUTS = {
    "nofence":   [("freeRetiredMorphs", "\n                && slot->audioReadingIdx.load (std::memory_order_acquire) != i", ""),
                  ("freeRetiredMorphs", "\n                && importGraceOver (slot->retiredAt[i]))", ")")],
    "nohold":    [("freeRetiredMorphs", "\n                && now - slot->retiredMs[i] >= kImportFreeHoldMs", "")],
    "cooldown":  [("freeRetiredMorphs", "slot->pending[i] = false;", "slot->pending[i] = false; slot->retireCooldown = 0;")],
    "stampeach": [("rebuildMorphIfNeeded", "publishMorph (slot, nullptr);",
                   "publishMorph (slot, nullptr); for (int i = 0; i < 2; ++i) { slot.retiredAt[i] = audioSeq_.load (std::memory_order_seq_cst);"
                   " slot.retiredMs[i] = juce::Time::getMillisecondCounter(); slot.pending[i] = true; }")],
}
AUDIO_READ = r"^[ \t]*const tw::Wavetable\* wavetableForOsc \(int osc, MorphSlot& slot, int presetIdx\) noexcept[ \t]*$"

def die (msg, code = 1):
    print ("extract_morph_life: " + msg, file = sys.stderr); sys.exit (code)

def balanced (src, start):
    """src[start:] up to the brace that closes the first '{' at or after start (inclusive)."""
    b = src.find ("{", start)
    if b < 0: die ("no body after offset %d" % start)
    depth = 0
    for i in range (b, len (src)):
        if src[i] == "{": depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0: return src[start:i + 1]
    die ("unbalanced body at offset %d" % start)

def main():
    args = [a for a in sys.argv[1:] if not a.startswith ("--")]
    mut = None
    if "--mutate" in sys.argv:
        k = sys.argv.index ("--mutate")
        mut = sys.argv[k + 1] if k + 1 < len (sys.argv) else None
        args = [a for a in args if a != mut]
        if mut not in MUTS: die ("unknown mutation %r (%s)" % (mut, "/".join (MUTS)), 2)
    if len (args) != 3: die ("usage: extract_morph_life.py <PluginProcessor.h> <PluginProcessor.cpp> <out.h> [--mutate M]", 2)
    hdr, cpp, out = args
    H = open (hdr, encoding = "utf-8").read()
    C = open (cpp, encoding = "utf-8").read()

    parts = ["// GENERATED by Tests/extract_morph_life.py from Source/PluginProcessor.h/.cpp — do not edit.",
             "// mutation: %s" % (mut or "none"), "#if ! defined (MORPH_LIFE_FUNCS)"]
    for s in ("ImportSlot", "MorphSlot"):
        m = re.search (r"^[ \t]*struct %s\b[^;{]*$" % s, H, re.M)
        if not m: die ("struct %s not found in %s" % (s, hdr))
        body = balanced (H, m.start())
        if not H[m.start() + len (body):].lstrip().startswith (";"): die ("struct %s is not followed by ';'" % s)
        parts.append (body + ";")
    m = re.search (AUDIO_READ, H, re.M)
    if not m: die ("wavetableForOsc (int osc, MorphSlot& slot, int presetIdx) not found in %s" % hdr)
    parts.append (balanced (H, m.start()))
    parts.append ("#else")
    funcs = {}
    for f in FUNCS:
        found = [x for x in re.finditer (r"^[^\n;{}]*\bTerrainAudioProcessor::%s\s*\([^;{]*\)[^;{]*$" % f, C, re.M)
                 if "//" not in x.group (0).split ("\n")[0]]
        if len (found) != 1: die ("definition of TerrainAudioProcessor::%s found %d times in %s" % (f, len (found), cpp))
        funcs[f] = balanced (C, found[0].start()).replace ("TerrainAudioProcessor::", "MorphLife::")
    if mut:
        for f, old, new in MUTS[mut]:
            if funcs[f].count (old) != 1: die ("mutation %s: anchor found %d times in %s" % (mut, funcs[f].count (old), f), 2)
            funcs[f] = funcs[f].replace (old, new)
    parts += [funcs[f] for f in FUNCS]
    parts.append ("#endif")
    open (out, "w", encoding = "utf-8").write ("\n\n".join (parts) + "\n")
    print ("extract_morph_life: %s -> %s (%d functions + wavetableForOsc, 2 structs, mutation %s)" % (cpp, out, len (FUNCS), mut or "none"))

main()
