#!/usr/bin/env python3
# ══════════════════════════════════════════════════════════════════════════════════════════════
#  extract_import_life.py — fb636 F1 · SLICE THE SHIPPING IMPORT-TABLE LIFETIME VERBATIM into a
#  header Tests/wt_pages_cert.cpp compiles (the extract_imports_scan.py idiom).
#
#      python3 Tests/extract_import_life.py <PluginProcessor.h> <PluginProcessor.cpp> <out.h> [--mutate M]
#
#  WHAT IS CUT. From the header: `struct ImportSlot` and `struct ImportRead` (brace-balanced, bytes as
#  they ship). From the .cpp: importGraceOver, claimImportBufLocked, publishImportLocked,
#  buildImportLocked, dropImportTable and freeRetiredImports, with ONE token rewritten:
#  `TerrainAudioProcessor::` -> `ImportLife::` (the cert's host class). The cert then drives these
#  exact bytes from four threads against real page-backed tables.
#
#  THE MUTATIONS (the generated header only; Source is never written). Each must fire exactly once,
#  or this exits 2 — a control that cannot fire is not a control:
#      nopin    claimImportBufLocked stops waiting out ImportRead pins     -> the pinned reader goes red
#      freepin  freeRetiredImports stops skipping a pinned buffer          -> the pinned reader goes red
#      nograce  claimImportBufLocked stops waiting out the audio block     -> the audio reader goes red
#
#  ⚠️ If any piece moves or is renamed this exits non-zero with the reason: a LOUD red, never a cert
#  that quietly compiles nothing.
# ══════════════════════════════════════════════════════════════════════════════════════════════
import re, sys

FUNCS = ["importGraceOver", "claimImportBufLocked", "publishImportLocked",
         "buildImportLocked", "dropImportTable", "freeRetiredImports"]
MUTS = {
    "nopin":   ("claimImportBufLocked", "\n           || slot.readers[idx].load (std::memory_order_seq_cst) != 0)", ")"),
    "freepin": ("freeRetiredImports",   "\n                && slot.readers[i].load (std::memory_order_seq_cst) == 0)", ")"),
    "nograce": ("claimImportBufLocked", "! importGraceOver (slot.retiredAt[idx])", "false"),
}

def die (msg, code = 1):
    print ("extract_import_life: " + msg, file = sys.stderr); sys.exit (code)

def balanced (src, start):
    """src[start:] up to the brace that closes the first '{' at or after start (inclusive)."""
    b = src.find ("{", start)
    if b < 0: die ("no body after offset %d" % start)
    depth = 0
    for i in range (b, len (src)):
        if src[i] == "{": depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0: return src[start:i + 1]
    die ("unbalanced body at offset %d" % start)

def main():
    args = [a for a in sys.argv[1:] if not a.startswith ("--")]
    mut = None
    if "--mutate" in sys.argv:
        k = sys.argv.index ("--mutate")
        mut = sys.argv[k + 1] if k + 1 < len (sys.argv) else None
        args = [a for a in args if a != mut]
        if mut not in MUTS: die ("unknown mutation %r (%s)" % (mut, "/".join (MUTS)), 2)
    if len (args) != 3: die ("usage: extract_import_life.py <PluginProcessor.h> <PluginProcessor.cpp> <out.h> [--mutate M]", 2)
    hdr, cpp, out = args
    H = open (hdr, encoding = "utf-8").read()
    C = open (cpp, encoding = "utf-8").read()

    parts = ["// GENERATED by Tests/extract_import_life.py from Source/PluginProcessor.h/.cpp — do not edit.",
             "// mutation: %s" % (mut or "none"), "#if ! defined (IMPORT_LIFE_FUNCS)"]
    for s in ("ImportSlot", "ImportRead"):
        m = re.search (r"^[ \t]*struct %s\b[^;{]*$" % s, H, re.M)
        if not m: die ("struct %s not found in %s" % (s, hdr))
        body = balanced (H, m.start())
        if not H[m.start() + len (body):].lstrip().startswith (";"): die ("struct %s is not followed by ';'" % s)
        parts.append (body + ";")
    parts.append ("#else")
    funcs = {}
    for f in FUNCS:
        m = re.search (r"^[^\n;{}]*\bTerrainAudioProcessor::%s\s*\([^;{]*\)[^;{]*$" % f, C, re.M)
        if not m: die ("definition of TerrainAudioProcessor::%s not found in %s" % (f, cpp))
        funcs[f] = balanced (C, m.start()).replace ("TerrainAudioProcessor::", "ImportLife::")
    if mut:
        f, old, new = MUTS[mut]
        if funcs[f].count (old) != 1: die ("mutation %s: anchor found %d times in %s" % (mut, funcs[f].count (old), f), 2)
        funcs[f] = funcs[f].replace (old, new)
    parts += [funcs[f] for f in FUNCS]
    parts.append ("#endif")
    open (out, "w", encoding = "utf-8").write ("\n\n".join (parts) + "\n")
    print ("extract_import_life: %s -> %s (%d functions, 2 structs, mutation %s)" % (cpp, out, len (FUNCS), mut or "none"))

main()
