#!/usr/bin/env python3
# fb602 — SLICE THE SHIPPING HELPERS OUT OF PluginEditor.cpp VERBATIM into a header the cert
# compiles.  Not a transcription: if the function body changes, the cert compiles the CHANGE.
#
# fb602 — WITH NO ARGUMENTS it self-checks instead of crashing: slices the six helpers out of
# Source/PluginEditor.cpp into a temp file and reports. That keeps `for f in Tests/*.py` clean and
# makes the slicer itself a bar — if a helper is renamed or stops being `static juce::X name (`,
# preset_path_cert.cpp stops compiling the shipping code and starts compiling nothing, which is
# exactly the silent failure this file exists to prevent.
import re,sys,os,tempfile
if len(sys.argv) < 3:
    d = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sys.argv = [sys.argv[0],
                sys.argv[1] if len(sys.argv) > 1 else os.path.join(d, 'Source', 'PluginEditor.cpp'),
                os.path.join(tempfile.gettempdir(), 'ti_helpers_selfcheck.h')]
    print('self-check (no args): %s -> %s' % (sys.argv[1], sys.argv[2]))
src=open(sys.argv[1],encoding='utf-8').read()
want=['terrainDataDir','terrainSettingsFile','terrainWavetablesDir','tiCardSlug','tiPresetDir','tiSafePresetName']
out=['// GENERATED by extract_helpers.py — verbatim slices of Source/PluginEditor.cpp. DO NOT EDIT.',
     '#pragma once','#include <juce_core/juce_core.h>','']
for w in want:
    m=re.search(r'^static\s+juce::\w+\s+'+w+r'\s*\(',src,re.M)
    if not m: sys.exit('NOT FOUND: '+w)
    i=src.index('{',m.end()); d=0
    for j in range(i,len(src)):
        if src[j]=='{': d+=1
        elif src[j]=='}':
            d-=1
            if d==0: break
    ls=src.rfind('\n',0,m.start())+1
    out.append('#line %d "PluginEditor.cpp"'%(src[:ls].count('\n')+1))
    out.append(src[ls:j+1]); out.append('')
open(sys.argv[2],'w',encoding='utf-8').write('\n'.join(out))
print('extracted %d helpers -> %s'%(len(want),sys.argv[2]))
