// ═════════════════════════════════════════════════════════════════════════════════════
//  flt_halfband_extracted.h — GENERATED by Tests/extract_halfband.py.  DO NOT EDIT.
//  Verbatim slices of Source/SynthVoice.h — the 2x half-band the plugin actually ships.
//  Regenerate:  python3 Tests/extract_halfband.py     Verify:  --check (or run any gate)
//  flt_measure.h re-cuts SynthVoice.h at RUNTIME and compares kHalfBandSrcHash below,
//  so a stale header cannot silently measure yesterday's oversampler again (fb604).
// ═════════════════════════════════════════════════════════════════════════════════════
#pragma once

namespace tw {

#line 75 "Source/SynthVoice.h"
    struct HalfBandCoefs
    {
        static constexpr float a0 = 0.0890947891f;   // branch A (prototype's even coefficients)
        static constexpr float a1 = 0.3083589660f;   // branch B (odd — carries the Z⁻¹)
        static constexpr float a2 = 0.5744241747f;   // branch A
        static constexpr float a3 = 0.8493897684f;   // branch B
    };

#line 84 "Source/SynthVoice.h"
    struct HbAllpass
    {
        float x1 = 0.0f, y1 = 0.0f;
        inline float process (float x, float a) noexcept
        { const float y = a * (x - y1) + x1; x1 = x; y1 = y; return y; }
        void reset() noexcept { x1 = y1 = 0.0f; }
    };

#line 93 "Source/SynthVoice.h"
    struct HbBranch
    {
        HbAllpass s0, s1;
        inline float process (float x, float c0, float c1) noexcept
        { return s1.process (s0.process (x, c0), c1); }
        void reset() noexcept { s0.reset(); s1.reset(); }
    };

#line 102 "Source/SynthVoice.h"
    struct HalfBandUp2x
    {
        HbBranch A, B;
        inline void process (float x, float& even, float& odd) noexcept
        {
            even = A.process (x, HalfBandCoefs::a0, HalfBandCoefs::a2);
            odd  = B.process (x, HalfBandCoefs::a1, HalfBandCoefs::a3);
        }
        void reset() noexcept { A.reset(); B.reset(); }
    };

#line 115 "Source/SynthVoice.h"
    struct HalfBandDown2x
    {
        HbBranch A, B;
        float oddZ = 0.0f;
        inline float process (float even, float odd) noexcept
        {
            const float a = A.process (even, HalfBandCoefs::a0, HalfBandCoefs::a2);
            const float b = B.process (oddZ, HalfBandCoefs::a1, HalfBandCoefs::a3);
            oddZ = odd;
            return 0.5f * (a + b);
        }
        void reset() noexcept { A.reset(); B.reset(); oddZ = 0.0f; }
    };

#line 29 "flt_halfband_extracted.h"
// FNV-1a/64 of the whitespace-canonicalised slices above, at generation time.
static constexpr unsigned long long kHalfBandSrcHash = 0xAD8835CDDFB9443FULL;
static constexpr int kHalfBandStructs = 5;

} // namespace tw
