#!/usr/bin/env python3
# ══════════════════════════════════════════════════════════════════════════════════════════════
#  extract_halfband.py — fb604 · SLICE THE SHIPPING 2x OVERSAMPLER OUT OF SynthVoice.h VERBATIM
#  into a header the measurement harness compiles.  Not a transcription: if the converter changes,
#  Tests/flt_measure.h compiles the CHANGE.
#
#      python3 Tests/extract_halfband.py                              # regenerate the header
#      python3 Tests/extract_halfband.py --check                      # exit 1 if it is STALE
#      python3 Tests/extract_halfband.py <src.h> <out.h>              # explicit paths
#
#  WHY IT EXISTS (fb604).  fb603 replaced the linear-interp/box-decimate 2x wrapper with the
#  polyphase all-pass half-band in Source/SynthVoice.h:74-126 — and Tests/flt_measure.h kept its
#  own hand-written COPY of the old one.  So every number the committed acceptance gate printed
#  for the 26 needsOversampling() types was about an oversampler the plugin does not have
#  (pessimistic by up to 5.0 dB at 20 kHz: the old cascade is exactly the base-rate FIR
#  [0.25,0.75] for an identity filter).  A gate that measures the wrong DSP is worse than no gate
#  because it is trusted.  The cure is structural, not another careful copy.
#
#  ⚠️ WHY A SLICE AND NOT `#include "SynthVoice.h"`.  SynthVoice.h pulls juce_audio_processors,
#  the wavetable/FM/granular/geode/harmonic/modal engines and Signalsmith Tones — ~40 s and a full
#  JUCE tree per harness build, for four all-pass sections.  Tests/shim/ exists precisely because
#  the filter harness compiles against three stub JUCE headers.  Slicing keeps that, and the
#  DRIFT is closed the same way extract_helpers.py closes it for the preset-path helpers: the
#  generated header carries a hash of the bytes it was cut from, and flt_measure.h RE-CUTS
#  SynthVoice.h at runtime and compares.  Stale header, edited source, or hand-edited copy — all
#  three print HALF-BAND SOURCE DRIFT and fail the gate.
# ══════════════════════════════════════════════════════════════════════════════════════════════
import os, re, sys

WANT = ["HalfBandCoefs", "HbAllpass", "HbBranch", "HalfBandUp2x", "HalfBandDown2x"]
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEF_SRC = os.path.join(ROOT, "Source", "SynthVoice.h")
DEF_OUT = os.path.join(ROOT, "Tests", "flt_halfband_extracted.h")


def slice_structs(src):
    """[(name, first-line-number, verbatim text)] for each WANT struct, brace-matched."""
    out = []
    for w in WANT:
        m = re.search(r"^[ \t]*struct\s+" + w + r"\s*$", src, re.M)
        if not m:
            m = re.search(r"^[ \t]*struct\s+" + w + r"\b", src, re.M)
        if not m:
            raise LookupError("NOT FOUND in SynthVoice.h: struct " + w)
        i = src.index("{", m.end())
        d = 0
        for j in range(i, len(src)):
            if src[j] == "{":
                d += 1
            elif src[j] == "}":
                d -= 1
                if d == 0:
                    break
        else:
            raise LookupError("unbalanced braces in struct " + w)
        j = src.index(";", j) + 1
        ls = src.rfind("\n", 0, m.start()) + 1
        out.append((w, src[:ls].count("\n") + 1, src[ls:j]))
    return out


def canon(pieces):
    """The bytes the hash is over: the struct text with runs of whitespace collapsed, so a
       reindent is not drift but a changed coefficient, operator or statement is."""
    return "\x1e".join(n + "\x1f" + re.sub(r"\s+", " ", t).strip() for n, _, t in pieces)


def fnv1a64(s):
    h = 0xCBF29CE484222325
    for b in s.encode("utf-8"):
        h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def generate(src_path, out_path):
    with open(src_path, "r", encoding="utf-8") as f:
        src = f.read()
    pieces = slice_structs(src)
    h = fnv1a64(canon(pieces))
    rel = os.path.relpath(src_path, ROOT)
    L = ["// ═════════════════════════════════════════════════════════════════════════════════════",
         "//  flt_halfband_extracted.h — GENERATED by Tests/extract_halfband.py.  DO NOT EDIT.",
         "//  Verbatim slices of %s — the 2x half-band the plugin actually ships." % rel,
         "//  Regenerate:  python3 Tests/extract_halfband.py     Verify:  --check (or run any gate)",
         "//  flt_measure.h re-cuts SynthVoice.h at RUNTIME and compares kHalfBandSrcHash below,",
         "//  so a stale header cannot silently measure yesterday's oversampler again (fb604).",
         "// ═════════════════════════════════════════════════════════════════════════════════════",
         "#pragma once", "", "namespace tw {", ""]
    for n, ln, t in pieces:
        L.append('#line %d "%s"' % (ln, rel))
        L.append(t)
        L.append("")
    L.append("#line %d \"flt_halfband_extracted.h\"" % (len(L) + 3))
    L.append("// FNV-1a/64 of the whitespace-canonicalised slices above, at generation time.")
    L.append("static constexpr unsigned long long kHalfBandSrcHash = 0x%016XULL;" % h)
    L.append("static constexpr int kHalfBandStructs = %d;" % len(pieces))
    L.append("")
    L.append("} // namespace tw")
    L.append("")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    return pieces, h


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    src = args[0] if len(args) > 0 else DEF_SRC
    out = args[1] if len(args) > 1 else DEF_OUT
    if check:
        # TWO comparisons, because they catch different lies and only one of them was here at
        # first. (a) the RECORDED hash vs the source: catches a stale header, i.e. SynthVoice.h
        # moved and nobody regenerated. (b) the header's OWN struct text vs the source: catches a
        # HAND-EDIT of the generated copy — one digit of a coefficient, say — which leaves the
        # recorded hash untouched and therefore sailed straight past (a). The runner's mutation
        # control does exactly that edit, and with only (a) in place it read FRESH: the control
        # that was supposed to prove this check works was proving the opposite.
        with open(src, "r", encoding="utf-8") as f:
            srcPieces = slice_structs(f.read())
        want = fnv1a64(canon(srcPieces))
        try:
            with open(out, "r", encoding="utf-8") as f:
                gen = f.read()
            got = int(re.search(r"kHalfBandSrcHash = 0x([0-9A-Fa-f]+)ULL", gen).group(1), 16)
        except Exception as e:
            print("STALE: %s unreadable/unparseable (%s)" % (os.path.relpath(out, ROOT), e))
            sys.exit(1)
        try:
            have = fnv1a64(canon(slice_structs(gen)))
        except LookupError as e:
            print("STALE: %s no longer contains the structs (%s)" % (os.path.relpath(out, ROOT), e))
            sys.exit(1)
        why = []
        if got != want:
            why.append("recorded hash 0x%016X != source 0x%016X (header is STALE — regenerate)" % (got, want))
        if have != want:
            why.append("the header's own struct TEXT hashes 0x%016X, not 0x%016X "
                       "(the generated copy was HAND-EDITED — regenerate)" % (have, want))
        ok = not why
        print("%s  %s  recorded 0x%016X  text 0x%016X  source 0x%016X%s"
              % ("FRESH " if ok else "STALE ", os.path.relpath(out, ROOT), got, have, want,
                 "" if ok else "\n        " + "\n        ".join(why)))
        sys.exit(0 if ok else 1)
    pieces, h = generate(src, out)
    print("extracted %d structs (%s) -> %s   hash 0x%016X"
          % (len(pieces), ", ".join(n for n, _, _ in pieces), os.path.relpath(out, ROOT), h))
