#!/usr/bin/env python3
"""fb638 — THE FACTORY TABLES LOSE THEIR "Terra - " PREFIX, AND NO PRESET LOSES ITS TABLE.

Max 2026-09-13: "no more Terra when it comes to the name … just have the name of the wave table … Terra can be a bank
for later." The 120 shipped tables are Resources/Wavetables/<Category>/Terra - <Name>.flac. A preset saved before this
change carries  ref:1|<Category>/Terra - <Name>.flac|<hash of the FILE'S BYTES>  (PresetAssets.h). So:
  * the files are MOVED (git mv), never re-encoded — the bytes, and therefore the hash, stay identical;
  * Source/WtFactoryAliases.h maps every legacy relative path to its current one, and the restore path consults it
    when the saved path is missing (PluginProcessor.cpp, the wtAsset ref branch).

    python3 rename_factory.py                 # dry run: prints the map, checks collisions, writes the header preview
    python3 rename_factory.py --apply         # git mv the files, verify md5s, write the header + renames_fb638.csv
"""
import csv, hashlib, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLUG = os.path.normpath(os.path.join(HERE, '..', '..'))
BANK = os.path.join(PLUG, 'Resources', 'Wavetables')
HDR  = os.path.join(PLUG, 'Source', 'WtFactoryAliases.h')
CSV  = os.path.join(HERE, 'renames_fb638.csv')
PREFIX = 'Terra - '
APPLY = '--apply' in sys.argv

def md5(p):
    h = hashlib.md5()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''): h.update(b)
    return h.hexdigest()

def builtin_names():
    src = open(os.path.join(PLUG, 'Source', 'PluginProcessor.cpp'), encoding='utf-8').read()
    m = re.search(r'SYN_OSC_A_WT_PRESET, 1 \},\s*"[^"]*",\s*juce::StringArray \{(.*?)\}\s*,', src, re.S)
    body = re.sub(r'//[^\n]*', '', m.group(1))
    return re.findall(r'"([^"]*)"', body)

# ── the map: from the CSV once applied (idempotent), else from the files on disk ──────────────
pairs = []
if os.path.exists(CSV):
    with open(CSV) as f:
        for r in csv.DictReader(f): pairs.append((r['legacy'], r['current'], r['md5']))
else:
    for cat in sorted(os.listdir(BANK)):
        d = os.path.join(BANK, cat)
        if not os.path.isdir(d): continue
        for fn in sorted(os.listdir(d)):
            if fn.endswith('.flac') and fn.startswith(PREFIX):
                pairs.append((cat + '/' + fn, cat + '/' + fn[len(PREFIX):], md5(os.path.join(d, fn))))

ok = True
cur_names = [os.path.splitext(os.path.basename(c))[0] for _, c, _ in pairs]
dup = sorted({n for n in cur_names if [x.lower() for x in cur_names].count(n.lower()) > 1})
bi  = builtin_names()
clash = sorted({n for n in cur_names if n.lower() in {b.lower() for b in bi}})
left  = [b for b in bi if b.lower().startswith('terra')]
print(f'  {len(pairs)} legacy tables; {len(dup)} duplicate current names; {len(clash)} clash with a built-in')
if len(pairs) != 120: print('  ✗ expected 120 legacy tables'); ok = False
if dup:   print('  ✗ duplicates:', dup); ok = False
if clash: print('  ✗ clash with built-in names:', clash, '(rename the BUILT-IN — built-ins are saved by index)'); ok = False
if left:  print('  ! built-ins still named Terra…:', left)

def emit_header(path):
    lines = [
        '#pragma once',
        '// ════════════════════════════════════════════════════════════════════════════════════════════════════',
        '//  fb638 — GENERATED by Design/wavetables/rename_factory.py. Do not edit by hand; re-run the script.',
        '//',
        '//  Max 2026-09-13: "no more Terra … just have the name of the wave table." The 120 shipped factory tables',
        '//  lost their "Terra - " prefix. A preset saved before carries  ref:1|<Category>/Terra - <Name>.flac|<hash>.',
        '//  The files were MOVED, never re-encoded, so the hash (over the file\'s bytes) still matches — only the',
        '//  path changed, and this table maps it. The restore path asks currentFor() when the saved path is missing.',
        '// ════════════════════════════════════════════════════════════════════════════════════════════════════',
        '#include <juce_core/juce_core.h>',
        '',
        'namespace tw::wtalias',
        '{',
        '    struct Pair { const char* legacy; const char* current; };',
        '',
        '    inline constexpr Pair kPairs[] =',
        '    {',
    ]
    for lg, cu, _ in pairs:
        lines.append('        { "%s", "%s" },' % (lg.replace('"', '\\"'), cu.replace('"', '\\"')))
    lines += [
        '    };',
        '',
        '    /** The current relative path for a legacy one ("" when it is not a legacy path). Separators are',
        '        compared as \'/\' and case-insensitively (the reference always speaks \'/\'; macOS and Windows file',
        '        systems are case-insensitive by default). */',
        '    inline juce::String currentFor (const juce::String& legacyRel)',
        '    {',
        '        const auto key = legacyRel.replaceCharacter (\'\\\\\', \'/\');',
        '        for (const auto& p : kPairs)',
        '            if (key.equalsIgnoreCase (juce::String::fromUTF8 (p.legacy)))',
        '                return juce::String::fromUTF8 (p.current);',
        '        return {};',
        '    }',
        '',
        '    /** A saved display name that is exactly a legacy file stem ("Terra - Saw Steps") becomes the current',
        '        stem ("Saw Steps"); any other name — one the user typed — is returned unchanged. */',
        '    inline juce::String currentName (const juce::String& savedName)',
        '    {',
        '        for (const auto& p : kPairs)',
        '        {',
        '            const auto lg = juce::String::fromUTF8 (p.legacy).fromLastOccurrenceOf ("/", false, false)',
        '                                                             .upToLastOccurrenceOf (".", false, false);',
        '            if (savedName.equalsIgnoreCase (lg))',
        '                return juce::String::fromUTF8 (p.current).fromLastOccurrenceOf ("/", false, false)',
        '                                                           .upToLastOccurrenceOf (".", false, false);',
        '        }',
        '        return savedName;',
        '    }',
        '}',
        '',
    ]
    open(path, 'w', encoding='utf-8').write('\n'.join(lines))

if not ok: sys.exit(1)
if not APPLY:
    prev = os.environ.get('RENAME_PREVIEW', '/tmp/WtFactoryAliases.preview.h')
    emit_header(prev)
    for lg, cu, _ in pairs[:4]: print(f'    {lg}  ->  {cu}')
    print(f'  dry run OK · header preview -> {prev}')
    sys.exit(0)

# ── apply: git mv, verify bytes, record ───────────────────────────────────────────────────────
moved = 0
for lg, cu, h in pairs:
    src, dst = os.path.join(BANK, lg), os.path.join(BANK, cu)
    if os.path.exists(dst) and not os.path.exists(src):
        if md5(dst) != h: print('  ✗ already moved but bytes differ:', cu); sys.exit(1)
        continue
    subprocess.check_call(['git', 'mv', src, dst], cwd=PLUG)
    if md5(dst) != h: print('  ✗ bytes changed in the move:', cu); sys.exit(1)
    moved += 1
with open(CSV, 'w', newline='') as f:
    w = csv.writer(f); w.writerow(['legacy', 'current', 'md5'])
    for r in pairs: w.writerow(r)
emit_header(HDR)
print(f'  applied: {moved} moved, {len(pairs)} mapped, md5 identical for all · wrote {HDR} and {CSV}')
