#pragma once
// ════════════════════════════════════════════════════════════════════════════════════════════════════
//  fb638 — GENERATED by Design/wavetables/rename_factory.py. Do not edit by hand; re-run the script.
//
//  Max 2026-09-13: "no more Terra … just have the name of the wave table." The 120 shipped factory tables
//  lost their "Terra - " prefix. A preset saved before carries  ref:1|<Category>/Terra - <Name>.flac|<hash>.
//  The files were MOVED, never re-encoded, so the hash (over the file's bytes) still matches — only the
//  path changed, and this table maps it. The restore path asks currentFor() when the saved path is missing.
// ════════════════════════════════════════════════════════════════════════════════════════════════════
#include <juce_core/juce_core.h>

namespace tw::wtalias
{
    struct Pair { const char* legacy; const char* current; };

    inline constexpr Pair kPairs[] =
    {
        { "Analog/Terra - Brownout.flac", "Analog/Brownout.flac" },
        { "Analog/Terra - Divider.flac", "Analog/Divider.flac" },
        { "Analog/Terra - Juno Chorus.flac", "Analog/Juno Chorus.flac" },
        { "Analog/Terra - Ladder.flac", "Analog/Ladder.flac" },
        { "Analog/Terra - PWM Duo.flac", "Analog/PWM Duo.flac" },
        { "Analog/Terra - Supersaw.flac", "Analog/Supersaw.flac" },
        { "Analog/Terra - Sync Lead.flac", "Analog/Sync Lead.flac" },
        { "Analog/Terra - Tape Wow.flac", "Analog/Tape Wow.flac" },
        { "Analog/Terra - Tri Core.flac", "Analog/Tri Core.flac" },
        { "Analog/Terra - VCO Drift.flac", "Analog/VCO Drift.flac" },
        { "Analog/Terra - VCO Sick.flac", "Analog/VCO Sick.flac" },
        { "Analog/Terra - Varishape.flac", "Analog/Varishape.flac" },
        { "Basic Shapes/Terra - Count.flac", "Basic Shapes/Count.flac" },
        { "Basic Shapes/Terra - Drawbar.flac", "Basic Shapes/Drawbar.flac" },
        { "Basic Shapes/Terra - Pulse Sweep.flac", "Basic Shapes/Pulse Sweep.flac" },
        { "Basic Shapes/Terra - Rectify.flac", "Basic Shapes/Rectify.flac" },
        { "Basic Shapes/Terra - Saw Steps.flac", "Basic Shapes/Saw Steps.flac" },
        { "Basic Shapes/Terra - Sine Bloom.flac", "Basic Shapes/Sine Bloom.flac" },
        { "Basic Shapes/Terra - Stairs.flac", "Basic Shapes/Stairs.flac" },
        { "Basic Shapes/Terra - Tilt.flac", "Basic Shapes/Tilt.flac" },
        { "Basic Shapes/Terra - Tri Steel.flac", "Basic Shapes/Tri Steel.flac" },
        { "Basic Shapes/Terra - Upshift.flac", "Basic Shapes/Upshift.flac" },
        { "Chaos/Terra - Bifurcate.flac", "Chaos/Bifurcate.flac" },
        { "Chaos/Terra - Bit Flip.flac", "Chaos/Bit Flip.flac" },
        { "Chaos/Terra - Chirikov.flac", "Chaos/Chirikov.flac" },
        { "Chaos/Terra - Devil.flac", "Chaos/Devil.flac" },
        { "Chaos/Terra - Diffuse.flac", "Chaos/Diffuse.flac" },
        { "Chaos/Terra - Gray Code.flac", "Chaos/Gray Code.flac" },
        { "Chaos/Terra - Henon.flac", "Chaos/Henon.flac" },
        { "Chaos/Terra - Pi Digits.flac", "Chaos/Pi Digits.flac" },
        { "Chaos/Terra - Prime Gap.flac", "Chaos/Prime Gap.flac" },
        { "Chaos/Terra - Rule 30.flac", "Chaos/Rule 30.flac" },
        { "Chaos/Terra - Shatter.flac", "Chaos/Shatter.flac" },
        { "Chaos/Terra - Sierpinski.flac", "Chaos/Sierpinski.flac" },
        { "Chaos/Terra - Tent.flac", "Chaos/Tent.flac" },
        { "Chaos/Terra - XOR Fold.flac", "Chaos/XOR Fold.flac" },
        { "Cinematic/Terra - Ash Fall.flac", "Cinematic/Ash Fall.flac" },
        { "Cinematic/Terra - Breath.flac", "Cinematic/Breath.flac" },
        { "Cinematic/Terra - Cathedral.flac", "Cinematic/Cathedral.flac" },
        { "Cinematic/Terra - Choral Dawn.flac", "Cinematic/Choral Dawn.flac" },
        { "Cinematic/Terra - Ember.flac", "Cinematic/Ember.flac" },
        { "Cinematic/Terra - Glass Edge.flac", "Cinematic/Glass Edge.flac" },
        { "Cinematic/Terra - Horizon.flac", "Cinematic/Horizon.flac" },
        { "Cinematic/Terra - Nebula.flac", "Cinematic/Nebula.flac" },
        { "Cinematic/Terra - Shimmer Ladder.flac", "Cinematic/Shimmer Ladder.flac" },
        { "Cinematic/Terra - Tide.flac", "Cinematic/Tide.flac" },
        { "Digital/Terra - Bit Ladder.flac", "Digital/Bit Ladder.flac" },
        { "Digital/Terra - Branch Y.flac", "Digital/Branch Y.flac" },
        { "Digital/Terra - CZ Reso.flac", "Digital/CZ Reso.flac" },
        { "Digital/Terra - Cheby Stack.flac", "Digital/Cheby Stack.flac" },
        { "Digital/Terra - Double FB.flac", "Digital/Double FB.flac" },
        { "Digital/Terra - Feedback Saw.flac", "Digital/Feedback Saw.flac" },
        { "Digital/Terra - Overload.flac", "Digital/Overload.flac" },
        { "Digital/Terra - PD Pulse.flac", "Digital/PD Pulse.flac" },
        { "Digital/Terra - Prime Comb.flac", "Digital/Prime Comb.flac" },
        { "Digital/Terra - Sine Bomb.flac", "Digital/Sine Bomb.flac" },
        { "Digital/Terra - Stack Three.flac", "Digital/Stack Three.flac" },
        { "Digital/Terra - Thirteen.flac", "Digital/Thirteen.flac" },
        { "Digital/Terra - Warp Fold.flac", "Digital/Warp Fold.flac" },
        { "Digital/Terra - XOR Dust.flac", "Digital/XOR Dust.flac" },
        { "Harmonic/Terra - Blade Cull.flac", "Harmonic/Blade Cull.flac" },
        { "Harmonic/Terra - Blade Rise.flac", "Harmonic/Blade Rise.flac" },
        { "Harmonic/Terra - Blade Splay.flac", "Harmonic/Blade Splay.flac" },
        { "Harmonic/Terra - Bronze Rise.flac", "Harmonic/Bronze Rise.flac" },
        { "Harmonic/Terra - Bronze Tide.flac", "Harmonic/Bronze Tide.flac" },
        { "Harmonic/Terra - Chant Rise.flac", "Harmonic/Chant Rise.flac" },
        { "Harmonic/Terra - Chant Terrace.flac", "Harmonic/Chant Terrace.flac" },
        { "Harmonic/Terra - Hornet Cull.flac", "Harmonic/Hornet Cull.flac" },
        { "Harmonic/Terra - Hornet Rise.flac", "Harmonic/Hornet Rise.flac" },
        { "Harmonic/Terra - Neon Rise.flac", "Harmonic/Neon Rise.flac" },
        { "Metallic/Terra - Bell Array.flac", "Metallic/Bell Array.flac" },
        { "Metallic/Terra - Cluster Forge.flac", "Metallic/Cluster Forge.flac" },
        { "Metallic/Terra - Golden Clang.flac", "Metallic/Golden Clang.flac" },
        { "Metallic/Terra - Gong Wash.flac", "Metallic/Gong Wash.flac" },
        { "Metallic/Terra - Hammer Mill.flac", "Metallic/Hammer Mill.flac" },
        { "Metallic/Terra - Iron Lung.flac", "Metallic/Iron Lung.flac" },
        { "Metallic/Terra - Pipe Resonant.flac", "Metallic/Pipe Resonant.flac" },
        { "Metallic/Terra - Ring Mod Anvil.flac", "Metallic/Ring Mod Anvil.flac" },
        { "Metallic/Terra - Sheet Rattle.flac", "Metallic/Sheet Rattle.flac" },
        { "Metallic/Terra - Spring Tension.flac", "Metallic/Spring Tension.flac" },
        { "Metallic/Terra - Stiff Bar.flac", "Metallic/Stiff Bar.flac" },
        { "Metallic/Terra - Turbine.flac", "Metallic/Turbine.flac" },
        { "Physical/Terra - Bars Glass.flac", "Physical/Bars Glass.flac" },
        { "Physical/Terra - Bars Wood.flac", "Physical/Bars Wood.flac" },
        { "Physical/Terra - Bells Gong.flac", "Physical/Bells Gong.flac" },
        { "Physical/Terra - Brass Blare.flac", "Physical/Brass Blare.flac" },
        { "Physical/Terra - Flute Breath.flac", "Physical/Flute Breath.flac" },
        { "Physical/Terra - Grand Strike.flac", "Physical/Grand Strike.flac" },
        { "Physical/Terra - Pluck Nail.flac", "Physical/Pluck Nail.flac" },
        { "Physical/Terra - Reed Bite.flac", "Physical/Reed Bite.flac" },
        { "Physical/Terra - Skin Drum.flac", "Physical/Skin Drum.flac" },
        { "Physical/Terra - Skin Tension.flac", "Physical/Skin Tension.flac" },
        { "Spectral/Terra - Bit Mask.flac", "Spectral/Bit Mask.flac" },
        { "Spectral/Terra - Comb Walk.flac", "Spectral/Comb Walk.flac" },
        { "Spectral/Terra - Dust.flac", "Spectral/Dust.flac" },
        { "Spectral/Terra - Fibonacci.flac", "Spectral/Fibonacci.flac" },
        { "Spectral/Terra - Fractal Shelf.flac", "Spectral/Fractal Shelf.flac" },
        { "Spectral/Terra - Hinge.flac", "Spectral/Hinge.flac" },
        { "Spectral/Terra - Holes.flac", "Spectral/Holes.flac" },
        { "Spectral/Terra - Odd Rotate.flac", "Spectral/Odd Rotate.flac" },
        { "Spectral/Terra - Prime Window.flac", "Spectral/Prime Window.flac" },
        { "Spectral/Terra - Shear.flac", "Spectral/Shear.flac" },
        { "Spectral/Terra - Sierpinski Spectral.flac", "Spectral/Sierpinski Spectral.flac" },
        { "Spectral/Terra - Sieve.flac", "Spectral/Sieve.flac" },
        { "Spectral/Terra - Tilt Arc.flac", "Spectral/Tilt Arc.flac" },
        { "Spectral/Terra - Zipper.flac", "Spectral/Zipper.flac" },
        { "Vocal/Terra - Choir.flac", "Vocal/Choir.flac" },
        { "Vocal/Terra - Cloud.flac", "Vocal/Cloud.flac" },
        { "Vocal/Terra - Comb Drift.flac", "Vocal/Comb Drift.flac" },
        { "Vocal/Terra - Consonant.flac", "Vocal/Consonant.flac" },
        { "Vocal/Terra - Density.flac", "Vocal/Density.flac" },
        { "Vocal/Terra - Growl.flac", "Vocal/Growl.flac" },
        { "Vocal/Terra - Hiss Chord.flac", "Vocal/Hiss Chord.flac" },
        { "Vocal/Terra - Nasal.flac", "Vocal/Nasal.flac" },
        { "Vocal/Terra - Pollen.flac", "Vocal/Pollen.flac" },
        { "Vocal/Terra - Sandstorm.flac", "Vocal/Sandstorm.flac" },
        { "Vocal/Terra - Shatter Vocal.flac", "Vocal/Shatter Vocal.flac" },
        { "Vocal/Terra - Throat.flac", "Vocal/Throat.flac" },
        { "Vocal/Terra - Tone Noise.flac", "Vocal/Tone Noise.flac" },
        { "Vocal/Terra - Vox Mask.flac", "Vocal/Vox Mask.flac" },
    };

    /** The current relative path for a legacy one ("" when it is not a legacy path). Separators are
        compared as '/' and case-insensitively (the reference always speaks '/'; macOS and Windows file
        systems are case-insensitive by default). */
    inline juce::String currentFor (const juce::String& legacyRel)
    {
        const auto key = legacyRel.replaceCharacter ('\\', '/');
        for (const auto& p : kPairs)
            if (key.equalsIgnoreCase (juce::String::fromUTF8 (p.legacy)))
                return juce::String::fromUTF8 (p.current);
        return {};
    }

    /** A saved display name that is exactly a legacy file stem ("Terra - Saw Steps") becomes the current
        stem ("Saw Steps"); any other name — one the user typed — is returned unchanged. */
    inline juce::String currentName (const juce::String& savedName)
    {
        for (const auto& p : kPairs)
        {
            const auto lg = juce::String::fromUTF8 (p.legacy).fromLastOccurrenceOf ("/", false, false)
                                                             .upToLastOccurrenceOf (".", false, false);
            if (savedName.equalsIgnoreCase (lg))
                return juce::String::fromUTF8 (p.current).fromLastOccurrenceOf ("/", false, false)
                                                           .upToLastOccurrenceOf (".", false, false);
        }
        return savedName;
    }
}
