#!/usr/bin/env python3
"""render_all.py — render Terrain's own electric-piano multisamples into the raw library, ready for torgc.

    python3 render_all.py [rhodes wurli clav pianet] [--raw DIR] [--jobs N]

Writes <raw>/TerrainModels/<Name>/ : Samples/*.wav (48 kHz 24-bit mono, each peak-normalised to −1 dBFS with its
true level in the SFZ `volume`), <Name>.sfz (attack layers + release/key-up regions), noise/*.wav + noise/README.txt
(acoustic key-down / key-up one-shots for the shared noise map), and the set's LICENSE / LICENSE-SOURCE.txt.
Deterministic: the same code renders the same files.
"""
from __future__ import annotations

import argparse
import importlib
import math
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import common as C          # noqa: E402

DEFAULT_RAW = os.path.expanduser("~/Developer/VST-Plugins/organics-library/raw")
MODELS = ["rhodes", "wurli", "clav", "pianet"]
DATE = "2026-09-24"
LICENCE_TEXT = f"""Terrain electric-piano models (TerrainModels/)
Licence: Proprietary-WavesCrate

Every audio file in this folder was generated by Waves Crate's own physical-model renderer
(plugins/Terrain/Tools/organics/epmodel in the Terrain repository), rendered {DATE}.
No third-party audio was used: the tones are computed from first principles (modal tines/reeds/strings, hammer/
tangent/pad contact models, electromagnetic and electrostatic pickup curves, filters). Some model parameters were
fitted to a handful of scalar MEASUREMENTS (harmonic levels, spectral centroid) of reference recordings; no reference
audio, impulse response or spectrum was copied, filtered, convolved or shipped.
The samples, mappings and noise one-shots are owned outright by Waves Crate. No permission or attribution is needed.
"""


def zones(roots, lo, hi):
    """Contiguous key zones around each root (split halfway between neighbours), covering lo..hi."""
    out = []
    for i, r in enumerate(roots):
        a = lo if i == 0 else (roots[i - 1] + r) // 2 + 1
        b = hi if i == len(roots) - 1 else (r + roots[i + 1]) // 2
        out.append((r, a, b))
    return out


def job(args):
    model, root, outdir = args
    mod = importlib.import_module(model)
    rows = []
    attack = root in mod.ROOTS
    ys = [mod.render(root, v) if (attack or i == mod.REF_LAYER) else None for i, (_, _, v) in enumerate(mod.LAYERS)]
    ref = C.rms_db(ys[mod.REF_LAYER])
    g = -18.0 - ref                                    # per-key level so every key sits alike at the reference layer
    for li, ((lv, hv, v), y) in enumerate(zip(mod.LAYERS, ys)):
        if not attack:
            break
        name = f"{mod.NAME}_{root:03d}_v{li + 1}.wav"
        applied = C.write_wav(os.path.join(outdir, "Samples", name), y * 10 ** (g / 20))
        rows.append(("attack", root, lv, hv, name, round(-applied, 3), len(y) / C.SR))
    if root in getattr(mod, "RELEASE_ROOTS", []):
        y = mod.render_release(root)
        name = f"{mod.NAME}_{root:03d}_rel.wav"
        applied = C.write_wav(os.path.join(outdir, "Samples", name), y * 10 ** (g / 20))
        rows.append(("release", root, 1, 127, name, round(-applied, 3), len(y) / C.SR))
    return rows


def render_model(model, raw, jobs):
    mod = importlib.import_module(model)
    outdir = os.path.join(raw, "TerrainModels", mod.NAME)
    os.makedirs(os.path.join(outdir, "Samples"), exist_ok=True)
    for f in os.listdir(os.path.join(outdir, "Samples")):
        os.remove(os.path.join(outdir, "Samples", f))
    rel_roots = list(getattr(mod, "RELEASE_ROOTS", []))
    todo = sorted(set(mod.ROOTS) | set(rel_roots))
    t0 = time.time()
    rows = []
    with ProcessPoolExecutor(jobs) as ex:
        for rs in ex.map(job, [(model, r, outdir) for r in todo]):
            rows.extend(rs)
    top = max(r[5] for r in rows if r[0] == "attack")
    # SFZ
    L = [f"// {mod.TITLE}", "// Generated by Tools/organics/epmodel/render_all.py — Waves Crate, Proprietary-WavesCrate.",
         f"// {len(mod.ROOTS)} zones x {len(mod.LAYERS)} velocity layers, 48 kHz 24-bit mono (DI).", "",
         "<control>", "default_path=Samples/", "", "<global>", "ampeg_attack=0.001", "ampeg_release=0.3", ""]
    L += ["<group> amp_veltrack=60", "// attack layers: loudness = the rendered physics (layer volumes) + a partial velocity curve"]
    for root, a, b in zones(mod.ROOTS, mod.KEY_LO, mod.KEY_HI):
        for r in sorted([r for r in rows if r[0] == "attack" and r[1] == root], key=lambda r: r[2]):
            L.append(f"<region> sample={r[4]} lokey={a} hikey={b} pitch_keycenter={root} lovel={r[2]} hivel={r[3]} "
                     f"volume={r[5] - top:.2f}")
    rel = [r for r in rows if r[0] == "release"]
    if rel:
        L += ["", "<group> trigger=release rt_decay=3", "// key-up: damper / tangent / pad contact through the pickup"]
        for root, a, b in zones(sorted(r[1] for r in rel), mod.KEY_LO, mod.KEY_HI):
            r = [x for x in rel if x[1] == root][0]
            L.append(f"<region> sample={r[4]} lokey={a} hikey={b} pitch_keycenter={root} volume={r[5] - top:.2f}")
    with open(os.path.join(outdir, f"{mod.NAME}.sfz"), "w") as f:
        f.write("\n".join(L) + "\n")
    # noises
    nd = os.path.join(outdir, "noise")
    os.makedirs(nd, exist_ok=True)
    for f in os.listdir(nd):
        os.remove(os.path.join(nd, f))
    rng = np.random.default_rng(C.RNG_SEED + MODELS.index(model))
    readme = [f"{mod.TITLE} — mechanical (acoustic) noise one-shots, Waves Crate model, Proprietary-WavesCrate.",
              "Each file is peak-normalised to -1 dBFS. The DI tone never contains these sounds, so map them as",
              "kind:\"noise\" regions (suggested authored level about -24 dB below the ff attack; 2 variants each →",
              "random round robin). Zones are MIDI key ranges.", "",
              "file | trig | zone (keys) | what it is"]
    for fname, trig, zone, y, what in mod.render_noises(rng):
        C.write_wav(os.path.join(nd, fname), y)
        lo, hi = mod.NOISE_ZONES[zone]
        readme.append(f"{fname} | {trig} | {zone} ({lo}-{hi}) | {what}")
    with open(os.path.join(nd, "README.txt"), "w") as f:
        f.write("\n".join(readme) + "\n")
    secs = sum(r[6] for r in rows)
    mb = sum(os.path.getsize(os.path.join(outdir, "Samples", r[4])) for r in rows) / 1048576
    print(f"{mod.NAME}: {len(rows)} samples, {secs:.0f} s audio, {mb:.0f} MB, {time.time() - t0:.0f} s")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("models", nargs="*", default=MODELS)
    ap.add_argument("--raw", default=DEFAULT_RAW)
    ap.add_argument("--jobs", type=int, default=max(1, (os.cpu_count() or 4) - 2))
    a = ap.parse_args()
    base = os.path.join(a.raw, "TerrainModels")
    os.makedirs(base, exist_ok=True)
    for n in ("LICENSE", "LICENSE-SOURCE.txt"):
        with open(os.path.join(base, n), "w") as f:
            f.write(LICENCE_TEXT)
    for m in a.models:
        render_model(m, a.raw, a.jobs)


if __name__ == "__main__":
    main()
